1. Image: images/products/SL_1001.jpg
   Product: WASH AND GLOSS CONCENTRATED
   Price: $9.99
   
2. Image: images/products/SL_1002.jpg
   Product: Streak Free Window Clean
   Price: $9.99
   
3. Image: images/products/SL_1003.jpg
   Product: EVEO Screen Cleaner Spray
   Price: $26.97
   
4. Image: images/products/SL_1004.jpg
   Product: Meguiar's G14716 Ultimate Protectant
   Price: $17.67
   
5. Image: images/products/SL_1005.jpg
   Product: 12H Nano Ceramic Coating 
   Price: $27.60
